/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package gt.util.lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class destination_t implements lcm.lcm.LCMEncodable
{
    public float des_x;
    public float des_y;
 
    public destination_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x2e4457f292d34f9fL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(destination_t.class))
            return 0L;
 
        classes.add(destination_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeFloat(this.des_x); 
 
        outs.writeFloat(this.des_y); 
 
    }
 
    public destination_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public destination_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static destination_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        destination_t o = new destination_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.des_x = ins.readFloat();
 
        this.des_y = ins.readFloat();
 
    }
 
    public destination_t copy()
    {
        destination_t outobj = new destination_t();
        outobj.des_x = this.des_x;
 
        outobj.des_y = this.des_y;
 
        return outobj;
    }
 
}

